### ISSUE TITLE
Block installing the same app twice with different crds

### ISSUE THREAD

**Issue by gbbirkisson** [enonic/xp-operator#116]
I can install the same app twice with different CRDs, like so:

```yaml
apiVersion: enonic.cloud/v1
kind: Xp7App
metadata:
  name: datatoolbox-2
spec:
  url: https://dl.bintray.com/rcd-systems/rcd-repo/systems/rcd/enonic/datatoolbox/5.0.2/datatoolbox-5.0.2.jar
---
apiVersion: enonic.cloud/v1
kind: Xp7App
metadata:
  name: datatoolbox-3
spec:
  url: https://dl.bintray.com/rcd-systems/rcd-repo/systems/rcd/enonic/datatoolbox/5.0.3/datatoolbox-5.0.3.jar
```

Currently this will cause these 2 CRDs to "compete", so 1 will install and run, then the other, and so on.

It is hard to block this because we do not have the app key until we install it.

One solution is for the operator to pre-download and analyse jars before trying to install, but that seems a bit much.
