### ISSUE TITLE
Vendor-specific instructions

### ISSUE THREAD

**Issue by thomasheartman** [enonic/xp-operator#136]
I don't know whether this is something we want to include in the
documentation or not, but I made some notes of what you have to do to
us the operator with the `simple.yaml` setup on GCP, Azure AKS, and
Digital Ocean. I'm including what I found below in case it's useful:

## GCP

To make the guide work as expected on a 'standard cluster', you need to lower the resource usage in your `values` file:

```yaml
config: |
  operator.charts.values.resources.cpu.defaultRequests=0.2
  operator.charts.values.resources.memory.defaultRequests=512Mi
```

Apart from this it almost worked flawlessly, except:

### Operator installation fails on 'autopilot' mode

It seems that GCP just launched *autopilot* k8s clusters that are easier to set up. These clusters are preconfigured with some of Google's best practices, but they also come with limitations as to what you can do. When trying to install the operator, I got the following error message:

    $ helm upgrade --install -n kube-system --version 0.7.1  enonic-operator enonic/operator
    Release "enonic-operator" does not exist. Installing it now.
    Error: rendered manifests contain a resource that already exists. Unable to continue with install: could not get information about the resource: mutatingwebhookconfigurations.admissionregistration.k8s.io "enonic-operator" is forbidden: User "the@enonic.com" cannot get resource "mutatingwebhookconfigurations" in API group "admissionregistration.k8s.io" at the cluster scope: GKEAutopilot authz: cluster scoped resource "mutatingwebhookconfigurations/" is managed and access is denied

## Azure AKS

Azure was reasonably simple to use. The `az` CLI got me everything I needed after creating an account. There was only one thing I had to configure: storage classes for the PVCs.

### Set storage class: `default`

Apparently, AKS doesn't have the `standard` K8s storage class available. The available options are listed under [the documentation for AKS storage classes](https://docs.microsoft.com/en-us/azure/aks/concepts-storage#storage-classes). I went with `default`, using this values file:

```yaml
config: |
  operator.charts.values.storage.shared.storageClassName=default
  operator.charts.values.storage.default.storageClassName=default
```

### Set storage class `do-block-storage`

Digital Ocean requires you to set storage type `do-block-storage` for your PVCs. We can do this by using a `values` file like this:

```yaml
config: |
  operator.charts.values.storage.shared.storageClassName=do-block-storage
  operator.charts.values.storage.default.storageClassName=do-block-storage
```

### change minimum storage reqs

Digital ocean failed to create PVCs with the provided `simple` config
because the PVC storage requirements of `100Mi` were below the minimum
of `1Gi`. In other words, the solution was to change this part of the
config:

```yaml
        # Volumes private to the node
        disks:
          - name: blobstore
            size: 100Mi
          - name: snapshots
            size: 100Mi
          - name: export  # Dumps and other data
            size: 100Mi
          - name: deploy  # Apps installed in the deploy folder
            size: 100Mi
          - name: index   # Node ES index
            size: 100Mi
          - name: work    # Node cache
            size: 100Mi
```

to this:

```yaml
        # Volumes private to the node
        disks:
          - name: blobstore
            size: 1Gi
          - name: snapshots
            size: 1Gi
          - name: export  # Dumps and other data
            size: 1Gi
          - name: deploy  # Apps installed in the deploy folder
            size: 1Gi
          - name: index   # Node ES index
            size: 1Gi
          - name: work    # Node cache
            size: 1Gi
```
