### ISSUE TITLE
Support CF SSL4SaaS (Custom Hostnames)

### ISSUE THREAD

**Issue by gbbirkisson** [enonic/xp-operator#272]
You need to add a new field to the `Domain` CRD to enable SSL4Saas:

```yaml
apiVersion: enonic.cloud/v1
kind: Domain
metadata:
  name: gummi-com
spec:
  host: gummi.com
  dnsRecord: false
  cdn: true
  ssl4Saas: true <-- This is new
  certificate:
    authority: selfSigned
```

Then you have to update [DNS Record handling](https://github.com/enonic/xp-operator/blob/master/java-operator/src/main/java/com/enonic/kubernetes/operator/domain/OperatorDomainDns.java) to act on that parameter.

Use the [CF api](https://api.cloudflare.com/#custom-hostname-for-a-zone-create-custom-hostname) to setup SSL4Saas (Custom Hostnames).

The CF token used by default for the operator probably also needs more permissions to be able to manage custom hostnames.
