### ISSUE TITLE
Add support to set env variables from k8s secret resource

### ISSUE THREAD

**Issue by danhul** [enonic/xp-operator#478]
Currently it's possible to set environment variables for xp7deployment resource as follows

```
nodegroups:
      ...
      env:
        - name: DEV_BRANCH_NAME
          value: "{{ .Env.BRANCH_NAME }}"
```

But if we need to set a value to an environment variable from a k8s secret resource the syntax is a bit different as shown below. But xp-operator doesn't recognize this syntax.

```
nodegroups:
      ...
      env:
         - name: DEV_BRANCH_NAME
            valueFrom:
               secretKeyRef:
                   name: branch-name
                   key: topsecret
```
